name: climb-token
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
plugins:
  - name: solidity
  - name: hardhat
  - name: etherscan
solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.2"
compiler:
  ignore_files:
    - "*README.md"
hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: "https://bscrpc.com"
        block_number: 27072900
