[profile.default]
src = "extendedContracts/src"
out = "extendedContracts/out"
test = "extendedContracts/test"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]